version: '2'

volumes:
  db:

services:
  postgres:
    build: ./postgres
    volumes:
      - db:/var/lib/postgresql/data
      - ./io:/io
    ports:
      - 5432:5432
  tesseract:
    image: tesseractshadow/tesseract4re
    command: tail -f /dev/null
    volumes:
      - ./ark_87287:/home/work
  sloan:
#    image: ucdlib/sloan-ocr
    build: ./dsi
    command: tail -f /dev/null
    volumes:
      - ./io:/io
      - ./dsi:/opt/dsi
